### ISSUE TITLE
`honeyalb`: Support publishing via OTLP

### ISSUE THREAD

**Issue by spencerwilson** [honeycombio/honeyaws#130]
Use case:

- I have traces representing HTTP requests that traverse multiple ALBs and application processes.
- I have OpenTelemetry Collector deployed as an agent on the hosts running the application processes.
- I want my traces to include spans for time spent in ALB hosts. The most valuable thing about these spans is that they'd provide the most accurate measurement of client-facing request latencies (at least short of instrumenting the clients).

Ideally I'd run `honeyalb` on a host that's also running the OpenTelemetry Collector as an agent, and instruct the former to send OTLP data to the latter.

In terms of new implementation work, it seems like this would involve writing at least

- a parser of the log data into OpenTelemetry data structures
- a publisher to send those structures via OTLP (gRPC variant is my preference, just because that's what people seem to recommend more) to somewhere else

AFAICT, `honeyalb` is the closest thing to streaming ALB access logs into an OpenTelemetry-based system that exists today, but if there's a way to do this today I would love to know about it! Thank you.

**Comment by spencerwilson** [comment]
Actually, I'm not so confident that there's a clear way to support this. In particular, successful transformation of ALB requests into OTel spans requires that

- processes which generate OTel spans from ALB access log entries (such as `honeyalb`) employ some deterministic algorithm to derive [SpanContext](https://github.com/open-telemetry/opentelemetry-specification/blob/52cc12879e8c2d372c5200c00d4574fa73996369/specification/trace/api.md#spancontext) from a log entry
- all other processes that the trace traverses propagate context in a compatible way. At minimum that means that
  1) If they're not contributing a span, they at least propagate incoming context.
  2) If they do contribute spans, they extract it from / inject it into HTTP headers in a sound way.

Concretely that probably would look like all processes using some matching [`TextMapPropagator`](https://github.com/open-telemetry/opentelemetry-specification/blob/52cc12879e8c2d372c5200c00d4574fa73996369/specification/context/api-propagators.md#textmap-propagator) when propagating , like a derivative of the JS SDK's [`HttpTraceContextPropagator`](https://github.com/open-telemetry/opentelemetry-js/blob/v0.23.0/packages/opentelemetry-core/src/trace/HttpTraceContextPropagator.ts#L67-L126) that knows how to read/write `X-Amzn-Trace-Id` req header (and possibly also the W3C `traceparent` and `tracestate` headers, too).

A good first thing to do would probably be to actually write up a lightweight "spec" on such a system of context propagation, to facilitate verifying that the propagation protocol itself is sound, before doing a bunch of implementation in some specific language.

**Comment by MikeGoldsmith** [comment]
Hey @spencerwilson - thanks for creating the issue. Sorry for the delay in getting back to you.

I agree adding OTLP export format to honeyalb is probably not the correct solution here. Have you seen that CloudWatch supports [OpenTelemetry](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Agent-open-telemetry.html)? You can use that to scrape telemetry from different AWS tools, then use a [Firehose](https://docs.amazonaws.cn/en_us/AmazonCloudWatch/latest/monitoring/CloudWatch-metric-streams-trustpolicy.html) to send that data to Honeycomb.

We’re going to close this for now. Feel free to re-open if it’s still relevant.

**Comment by spencerwilson** [comment]
Thanks for the response @MikeGoldsmith ! Looks like the CloudWatch agent runs on EC2 instances, to help ferry application telemetry to its eventual storage. That's fine, but doesn't seem related to what `honeyalb` does: transforms ALB access logs into spans and ships that data to another destination.

Not sure if that renders this issue as "still relevant", so I'm cautiously gonna re-open this issue haha

**Comment by spencerwilson** [comment]
jk, I'm not authorized to re-open issues in this repo!
