### ISSUE TITLE
ELBv2 support (ALB + NLB)

### ISSUE THREAD

**Issue by garthk** [honeycombio/honeyaws#14]
… because you're using the v1 API. I tried hacking and slashing, but I'm running out of time. Work so far:
* copy `github.com/aws/aws-sdk-go/service/elbv2` into `vendor/`
* import it
* in `cmdELB`:
  ```
	elbSvc := elbv2.New(sess)
	describeLBResp, err := elbSvc.DescribeLoadBalancers(&elbv2.DescribeLoadBalancersInput{})
  // ...
	if len(args) > 0 {
		switch args[0] {
		case "ls":
			for _, lb := range describeLBResp.LoadBalancers {
				fmt.Println(*lb.LoadBalancerName)
			}
  // ...
			// Use all available load balancers by default if none
			// are provided.
			if len(lbNames) == 0 {
				for _, lb := range describeLBResp.LoadBalancers {
					lbNames = append(lbNames, *lb.LoadBalancerName)
				}
			}
  ```
* in `ingestLBLogs`, where I'm doing extra work to keep taking `lbName` as an argument instead of an ARN:
  ```
	elbSvc := elbv2.New(sess, nil)
	describeLBResp, err := elbSvc.DescribeLoadBalancers(&elbv2.DescribeLoadBalancersInput{
		Names: []*string{
			aws.String(lbName),
		},
	}) // not walking token because there should be only one
	if err != nil {
		fmt.Fprintln(os.Stderr, "Error describing LBs: ", err)
		os.Exit(1)
	}
	if len(describeLBResp.LoadBalancers) == 0 {
		fmt.Fprintln(os.Stderr, "Couldn't find load balancer named", lbName)
		os.Exit(1)
	}
	lbArn := describeLBResp.LoadBalancers[0].LoadBalancerArn
	lbResp, err := elbSvc.DescribeLoadBalancerAttributes(&elbv2.DescribeLoadBalancerAttributesInput{
		LoadBalancerArn: lbArn,
	})
	if err != nil {
		fmt.Fprintln(os.Stderr, "Error describing load balancers: ", err)
		os.Exit(1)
	}
	enabled := false
	bucketName := ""
	bucketPrefix := ""
	for _, element := range lbResp.Attributes {
		fmt.Fprintln(os.Stderr, *element.Key, *element.Value)
		if *element.Key == "access_logs.s3.enabled" && *element.Value == "true" {
			enabled = true
		}
		if *element.Key == "access_logs.s3.bucket" {
			bucketName = *element.Value
		}
		if *element.Key == "access_logs.s3.prefix" {
			bucketPrefix = *element.Value
		}
	}
	if !enabled {
		fmt.Fprintf(os.Stderr, `Access logs are not configured for ELB %q. Please enable them to use the ingest tool.
  ```

… at which point, a change in the filenames is blocking me and I'm out of my time box.

If the ARN is `arn:aws:elasticloadbalancing:REGION:9999999999999:loadbalancer/app/LBNAME/UUID`, then the filename is `9999999999999_elasticloadbalancing_REGION_LBNAME. UUID_TIMESTAMP_IPADDR_RANDOMDIGITS.log.gz`.

I'm also concerned ELBv1 balancers won't show through the ELBv1 API and we'll have to break out the code for each service.

**Comment by nathanleclaire** [comment]
Yeah, we'll likely add an additional integration specifically for ELBV2. ELBV2, is it the exact same as ALB?

**Comment by garthk** [comment]
People use the terms interchangeably. And, now, you've got [NLB](https://aws.amazon.com/about-aws/whats-new/2017/09/announcing-network-load-balancer-for-elastic-load-balancing/) to worry about.

**Comment by nathanleclaire** [comment]
ALB is shipped into master! There are some notes to get started at https://honeycomb.io/docs/connect/aws-elastic-load-balancer/.

As for NLB, I seem to recall looking for a way to get access logs for it and couldn't find any? Please let me know if I'm mistaken and we can open a separate issue for that.
