### ISSUE TITLE
honeyalb: More dynamic limiting of ALB names to import from?

### ISSUE THREAD

**Issue by antifuchs** [honeycombio/honeyaws#152]
**Is your feature request related to a problem? Please describe.**

We run the aws-load-balancer-controller in kubernetes, which generates ALBs for Ingress objects defined in k8s. That means that the names of ALBs aren't stable over the lifetime of our deployment. We *could* import all the ALBs in our account, but that isn't an option for us (and I'm not sure if honeyaws re-lists all the existing ALBs in regular intervals).

**Describe the solution you'd like**

I would love if honeyalb could either:

* Let us specify a regex for the ALB names to import from, and listed the existing ALBs regularly, selecting the matching ones
* exit after a certain amount of number of polls that yielded no results (so it gets restarted by a supervisor and picks up the new ALB names).

**Describe alternatives you've considered**

I'm currently manually killing the honeyalb pod, which is the worst of all worlds: we miss trace spans, and this cleanup actino gets forgotten.

**Additional context**

**Comment by antifuchs** [comment]
One thing that we have found that might work is to run a second container that does a periodic diff of the ALBs we _would_ ingest from vs. the ones that we started with; if they change, a liveness probe turns unhealthy & the pod is restarted. I think that ought to work similarly well, but ofc it would be much nicer if we could do this in honeyalb directly (:

**Comment by ismith** [comment]
To be clear - would it solve your need to log all albs that are both:
- owned by the alb ingress controller in a particular cluster
and
- have s3 logging on
?

Or do you only want a subset of your k8s ingresses to send to honeycomb?

**Comment by antifuchs** [comment]
I think ingesting _all_ ALB logs might work for some, but not for our use case: We have a shared AWS account that contains several development stacks (prod is separate, but all dev stacks live in this one). 

That means every developer's ALB logs would be ingested into each developer's honeycomb tracing dataset (including those ALBs that have nothing to do with their own requests), and I'd really like to avoid that duplication. The only way I found to restrict honeyalb imports was by name, and so here we are (:
