### ISSUE TITLE
honeycloudtrail: support state files in s3 or other non-local storage

### ISSUE THREAD

**Issue by antifuchs** [honeycombio/honeyaws#192]
**Is your feature request related to a problem? Please describe.**

We're running honeycloudtrail in ECS/Fargate, and on Fargate, there are no really satisfying ways of storing persisted files locally available: The only one that I could find is EFS, and that hit a bit of resistance internally. (I am personally also not extremely excited about NFS-as-a-service, but if it's the only thing that will work...))

**Describe the solution you'd like**

Ideally, honeycloudtrail would let us store the state in a more ... cloud-aware way. Be that S3, or one of the several aws-provided databases (dynamodb, for example). I don't much mind which mechanism it is, but it would be really good to have one.

**Describe alternatives you've considered**

I think it's fine to mandate a local state file, but for something that's as tied to aws as the cloudtrail-consuming program in the honeyaws suite of tools, it does seem a bit unfortunate to tie us operators into these not-ready-for-stateless-operations kind of operative modes (:

**Comment by robbkidd** [comment]
Hi, @antifuchs!

I am also allergic to NFS, so I'm with you there. Have you and your team considered [the High Availability option](https://github.com/honeycombio/honeyaws#high-availability) to store state in DynamoDB instead of on local disk?

**Comment by antifuchs** [comment]
Hah, ooooops, I think we totally missed the `--highavail` option and assumed it just didn't exist. This will fix our issue & is a very pleasing solution. Thank you!
