### ISSUE TITLE
honeyalb for blue/green deployments

### ISSUE THREAD

**Issue by davidojedalopez** [honeycombio/honeyaws#51]
Our infrastructure works with blue/green deployments which means that everytime we deploy a new version of our app new load balancers get created and older ones destroyed. 

honeyalb seems to just be polling available load balancers at the time of the service startup. Having the service to regularly poll for new balancers can avoid additional steps on your customers' deployment flow.

@maplebed was kind enough to assist me with this on Intercom and added this issue to your internal tracker too.

**Comment by MikeGoldsmith** [comment]
We’re going to close this for now. Feel free to re-open if it’s still relevant.
