### ISSUE TITLE
`honeyelb ingest` does not handle NLBs gracefully

### ISSUE THREAD

**Issue by BRMatt** [honeycombio/honeyaws#54]
We have an ALB and an NLB in our account. An NLB proxies TCP connections and (seemingly) doesn't allow you to do any kind of access logging.

We would like to run `honeycomb ingest` without specifying load balancers to have the ingester pull in logs for all ALBs that have access logging enabled (and ignore those that don't with a warning), but the command is exiting because it cannot detect access logging as being enabled on the NLB:

```
INFO[2018-09-04T15:13:25Z] State tracking enabled - using local file system.
INFO[2018-09-04T15:13:25Z] Attempting to ingest ALB                      lbName=dev-vpc-ssh-ingress
Access logs are not configured for ALB "dev-vpc-ssh-ingress". Please enable them to use the ingest tool.

For reference see this link:

http://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-access-logs.html#enable-access-logging
```

We would expect the command to filter LBs that it can't ingest from and only ingest from those it can.

**Comment by nathanleclaire** [comment]
Gotcha - good point, you probably have figured this out but as a workaround you can specify the LB names directly in the command invocation.

**Comment by MikeGoldsmith** [comment]
We’re going to close this for now. Feel free to re-open if it’s still relevant.
