### ISSUE TITLE
Option to *not* exit when logging is not enabled and multiple ingest targets are set

### ISSUE THREAD

**Issue by fernandrone** [honeycombio/honeyaws#64]
So this is my use case: I want to run a single `honeyelb` and `honeycloudfront` daemon to ingest all logs from all loadbalancers and all cloudfront distributions, so far so good. However, as soon as the binary hits one single balancer or distribution that does not have logging enabled, it terminates with an error:

```
Access logs are not configured for ELB "<redacted>". Please enable them to use the ingest tool.
For reference see this link:
http://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-access-logs.html#enable-access-logging
```

Surely this makes a lot of sense when a single target is specified, or even a list of targets. However, when running the command with no targets, so it discovers all targets in my infrastructure:

```
$ honeyelb ingest
$ honeycloudfront ingest
```

I would expect it to download from all targets that have logging enabled. Alternatively it could log an error or warning message at every cycle (or at startup time) about targets that don't have logging enabled. 

Of course, enabling logging fixes it. But if someone - unaware of this limitation - creates a new load balancer or cloudfront distribution, suddenly on the next restart the daemon will break! The other alternative is to create a different daemon for every single instance I want monitored, but this introduces a lot of overhead and defeats the purpose of using a single binary to monitor all targets.

I'll add a comment with a few suggestions and will gladly open a pull request if there's support for this.

**Comment by MikeGoldsmith** [comment]
We’re going to close this for now. Feel free to re-open if it’s still relevant.
