### ISSUE TITLE
X-Amzn-Trace-Id parsing incompatible with beelines and AWS sdk

### ISSUE THREAD

**Issue by paulosman** [honeycombio/honeyaws#71]
The elastic load balancing parsers interpret the value of incoming X-Amzn-Trace-Id headers according to the format documented here:

https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-request-tracing.html

Specifically, split on `;` and then key/value pairs separated by `=`. Each value (e.g. `1-5e7e30bc-b1809948e6800da0555495d8`) is then treated as a hyphen separated string with version, timestamp, and identifier. The identifier is then used as the `trace.trace_id` and `trace.span_id` for the event sent to Honeycomb. 

This makes sense but is incompatible with parsers that treat the value as an opaque identifier. Mixing and matching parsing algorithms will result in broken traces. The AWS SDKs seem to treat the id as an opaque string: https://github.com/aws/aws-xray-sdk-node/blob/master/packages/core/lib/utils.js#L176

**Comment by nathanleclaire** [comment]
No strong opinions on this one, I trust your best judgment. Mild preference for breaking honeyaws as it's less commonly used than Beeline.

The parsing in ALB is more experimental than anything (i.e., "Wouldn't it be cool if you could get traces just from the logs")
